paths:
  input_data_path: "data/raw/heart_cleveland_upload.csv"
  output_model_path: "models/model.pkl"
  metric_data_path: "metrics/metrics.json"

splitting_params:
  val_size: 0.2
  random_state: 42

train_params:
  model_type: "LogisticRegression"
  params:
    random_state: 42

feature_params:
  preprocess:
    numerical_preprocessor: "StandardScaler"
    numerical_columns:
        - "age"
        - "trestbps"
        - "chol"
        - "thalach"
        - "oldpeak"
    categorical_preprocessor: "OneHotEncoder"
    categorical_columns:
        - "cp"
        - "restecg"
        - "slope"
        - "ca"
        - "thal"
  target_col: "condition"

metrics:
  - "accuracy_score"
  - "precision_score"
  - "recall_score"
  - "roc_auc_score"
